name: parkinglot
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"


dependencies:
  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.0.0
  cloud_firestore: ^3.1.5
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"


flutter:
  uses-material-design: true
  assets:
     - assets/logo.png
     - assets/logo2.png
  
  

 